[package]
name = "portfolio-tera-axum"
version = "0.1.0"
edition = "2024"

[dependencies]
tera = "1"
serde = { version = "1.0.219", features = ["derive"] }
axum = "0.8.4"
tower-http = {version = "0.6.6", features = ["fs"]}
tokio = { version = "1.46.1", features = ["full"] }