[phases.build]
cmds = ["cargo build --release"]

[phases.install]
# Copy the binary to where Railway expects it
cmds = ["mkdir -p /app/bin", "cp /app/target/release/portfolio-tera-axum /app/bin/portfolio-tera-axum"]

[start]
cmd = "/app/bin/portfolio-tera-axum"